### PR TITLE
bump version to 0.1.18

### PR DESCRIPTION
**Pull request by andrewsykim**
cc @scottrobertson should have fix for https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/117

### CODE REVIEW

**Comment by fatih** [comment]
lgtm

@andrewsykim did you use the new release task in the Makefile? Curious about your thougts, would be nice if you see any issues there or have any feedbacks. We use the same in the CSI repo with success, but the more people use it the more we have a good understanding of using it :)

**Comment by fatih** [comment]
lgtm

@andrewsykim did you use the new release task in the Makefile? Curious about your thougts, would be nice if you see any issues there or have any feedbacks. We use the same in the CSI repo with success, but the more people use it the more we have a good understanding of using it :)

**Comment by andrewsykim** [comment]
@fatih overall it works well! One caveat is managing kubernetes version dependencies as we bump versions here but that's not necessarily an issue with the tool/target but more of a release management problem.

**Comment by Ratedev** [comment]
will this be released soon? i would really like to use this feature.

**Comment by andrewsykim** [comment]
Sorry for the delay! I'll release this shortly

**Pull request merged**
