### PR TITLE
Migrate from go dep to Go modules.

### PR DESCRIPTION
**Pull request by timoreimann**
As a side effect, we hope to simplify upgrading to a more recent version of the Kubernetes dependencies (which has been someone difficult with go dep, see also #165).

- Run `go mod init`.
- Remove Go versions not supporting Go modules from Travis.
- Use Go 1.12.3 for building.
- Vendor golint through tools.go approach.
- Remove go dep's Gopkg.toml.
- Update vendor folder.

### CODE REVIEW

**Comment by timoreimann** [comment]
@nanzhong @jcodybaker @fatih PTAL

**Comment by fatih** [comment]
One last question. Did you run `go mod tidy` before opening this? I know it's part of the new `vendor` task in the makefile, but wasn't sure if you have called it or not.

lgtm

**Comment by timoreimann** [comment]
@fatih just ran `make vendor` again to be sure: all vendored dependencies are tidied up and in order.

We probably want another script in the future that validates all vendored files have been properly added through gomod and run that during CI. That's for a future PR.

**Pull request merged**
