### PR TITLE
Update Deployment apiVersion to apps/v1

### LINKED ISSUE #285: Update repository manifests from extensions/v1beta1 to apps/v1
Kubernetes 1.16 stopped serving `extensions/v1beta{1,2}` API versions in favor of `apps/v1`. Hence, we need to bump the versions in all Kubernetes manifests we have in the repository and also [add the required label selectors](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#selector).

### PR DESCRIPTION
**Pull request by hypnoglow**
Updates apiVersion for Deployments in example manifests to apps/v1

Fixes #285

### CODE REVIEW

**Comment by timoreimann** [comment]
Looking good and working perfectly -- thanks a lot for your contribution, @hypnoglow. 👏

**Comment by hypnoglow** [comment]
Thanks! Happy Hacktoberfest! :)

**Comment by maniis** [comment]
@hypnoglow it looks you missed some of manifest files.
@timoreimann please review #287

**Comment by hypnoglow** [comment]
@maniis What do you mean? I don't think that manifests in "releases" directory should be updated, because they are already "released" and that might be a breaking change.

**Comment by MattIPv4** [comment]
Hey, @hypnoglow - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Pull request merged**
