### PR TITLE
vendor: update k8s.io packages to v1.13.2

### PR DESCRIPTION
**Pull request by MorrisLaw**
Update Kubernetes version.

### CODE REVIEW

**Comment by timoreimann** [comment]
@MorrisLaw thanks for your PR.

Unfortunately, the CI is complaining; apparently some types are misaligned now. :( Haven't looked into yet -- at least in the past, client-go and related friends would break occasionally and require adjusting accordingly.

**Comment by MorrisLaw** [comment]
Yeah, unfortunately "/  I plan on continuing to go through and adjust the necessary code. I'll let you know if I have any questions. Thank you @timoreimann !

**Comment by timoreimann** [comment]
Hey @MorrisLaw, we have moved to Go modules by now and upgraded the Kubernetes dependencies to 1.14. Hope you don't mind me closing this PR, thanks for kickstarting things (I partially based my work on yours)!

**Comment by MorrisLaw** [comment]
Thank you @timoreimann !

**Pull request closed without merging**
