### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ayrotideysarkar**
is this  okay now?
can you please merge my pull request?

### CODE REVIEW

**Comment by timoreimann** [comment]
Could you please close this PR and update the initial one you created? There's no need to create separate PRs for addressing suggestions.

**Comment by ayrotideysarkar** [comment]
I have closed my previous PR, So can you merge this PR?

**Comment by ayrotideysarkar** [comment]
Can you please accept my PR?

**Comment by timoreimann** [comment]
It'd be ideal if you could close out this PR, reopen the original one, and address the comments there for the sake of continuity of the review process.

**Comment by ayrotideysarkar** [comment]
Done.
now can you merge it?

**Pull request closed without merging**
