### PR TITLE
release v0.1.3

### PR DESCRIPTION
**Pull request by andrewsykim**
cc @klausenbusk

### CODE REVIEW

**Comment by xmudrii** [comment]
I guess this is irrelevant and is very tiny nitpick but I've found one occurrence of `0.1.2` in the README file (example under CCM heading -- https://github.com/digitalocean/digitalocean-cloud-controller-manager#cloud-controller-manager).

**Comment by andrewsykim** [comment]
@xmudrii good catch, that part of the README is just an example but it should be more generic. I'll update that :)

**Comment by klausenbusk** [comment]
I'm wondering if there is a better approach than duplicating the manifest file on every release?

**Comment by bhcleek** [comment]
LGTM

I think we can work out something better with the manifest separately.

**Comment by andrewsykim** [comment]
Agreed, the release file seems unnesscary now since we're only updating image tags, but the idea was that it makes more complicated updates easier in the future.

**Pull request merged**
