### PR TITLE
[load_balancer] add annotation for redirect_http_to_https option

### PR DESCRIPTION
**Pull request by peterver**
Add the option to specify redirect_http_to_https on the DO load balancer resource using the annotation

```
service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https
```

As per the specification at https://developers.digitalocean.com/documentation/v2/#load-balancers this defaults to false.

### CODE REVIEW

**Comment by andrewsykim** [comment]
Hey @peterver changes look great! 

Can we add a test case for the redirect annotation [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/do/loadbalancers_test.go#L1083). Otherwise I think we're good to :shipit:.

**Comment by peterver** [comment]
@andrewsykim will do ! :)

**Comment by peterver** [comment]
@andrewsykim I've added a test case for the getRedirectHttpToHttps function, any other test case you would like me to look at ?

**Comment by peterver** [comment]
@andrewsykim I added the buildLoadBalancerRequest test for http_to_https redirect :)

**Comment by andrewsykim** [comment]
LGTM! Thanks!

**Pull request merged**
